Throw an error if no address in payments file
online-create-transaction --wallet wallet-settlement-wallet-001.json
--payments ~/Desktop/publishers-20180103-160617-456.json
(node:26467) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use
'global'
/Users/mrose/Documents/Projects/brave.com/brave-payments-tools/cli.js:28
6
          if (!entry.address) throw new Error('undefined address for '
+ JSON.stringify(entry))
                              ^

Error: undefined address for
{"publisher":"chrisruppel.com","altcurrency":"BAT","probi":"108429297090
45949482","fees":"570680511002418393","authority":"github:mrose17","tran
sactionId":"64e5d92f-3f7c-4f7a-84c1-476e260f48ca","currency":"LTC"}
    at details.forEach
(/Users/mrose/Documents/Projects/brave.com/brave-payments-tools/cli.js:2
86:37)
    at Array.forEach (<anonymous>)
    at fs.readFile
(/Users/mrose/Documents/Projects/brave.com/brave-payments-tools/cli.js:2
85:17)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)